### ISSUE TITLE
 invalid or reserved value found for <EExtendedProtocolDiscriminator> with value <208>

### ISSUE THREAD

**Issue by regek** [aligungr/UERANSIM#100]
Hi,

Initial-registration produces following error and gnb crashes: 
There are no errors on AMF side. 

All values for gnb and ue are default. 

```
tr.havelsan.ueransim.core.exceptions.ReservedOrInvalidValueException: invalid or reserved value found for <EExtendedProtocolDiscriminator> with value <208>
        at tr.havelsan.ueransim.nas.core.ProtocolEnum.fromValueGeneric(ProtocolEnum.java:71)
        at tr.havelsan.ueransim.nas.impl.enums.EExtendedProtocolDiscriminator.fromValue(EExtendedProtocolDiscriminator.java:42)
        at tr.havelsan.ueransim.nas.NasDecoder.nasPdu(NasDecoder.java:66)
        at tr.havelsan.ueransim.nas.NasDecoder.nasPdu(NasDecoder.java:49)
        at tr.havelsan.ueransim.nas.NasDecoder.nasPdu(NasDecoder.java:60)
        at tr.havelsan.ueransim.api.nas.NasSecurity.decryptNasMessage(NasSecurity.java:62)
        at tr.havelsan.ueransim.api.ue.UserEquipment.receiveNas(UserEquipment.java:77)
        at tr.havelsan.ueransim.api.ue.UserEquipment.cycle(UserEquipment.java:118)
        at tr.havelsan.ueransim.core.threads.NodeLooperThread.run(NodeLooperThread.java:50)
```
with value <**208**> this values changes. App log is also attached. 
[app.log](https://github.com/aligungr/UERANSIM/files/5097944/app.log)
Thanks

**Comment by aligungr** [comment]
I suspect there is a bug on free5gc side. Do you have a pcap file related to this error? (If not, you can capture with wireshark or tcpdump.)

**Comment by regek** [comment]
I ve attached the pacp file from the error as well log file from the free5gc

[log.zip](https://github.com/aligungr/UERANSIM/files/5105503/log.zip)
[Free5gcc_log.txt](https://github.com/aligungr/UERANSIM/files/5105505/Free5gcc_log.txt)

Please let me know if you need more information
Thanks

**Comment by aligungr** [comment]
According to pcap file, AMF either sends an incorrect/invalid or encrypted NAS message as Security Mode Command. However SecurityModeCommand should not be encrypted but only integrity protected. Even if so, the security header type claims that the message is not encrypted.

In short, apparently there is a bug on free5gc side.

**Comment by aligungr** [comment]
@regek I created an issue on free5gc side about this problem.

See https://github.com/free5gc/free5gc/issues/104.

**Comment by mazengxie** [comment]
I meet the same problems，can you solve it?
