### ISSUE TITLE
Exception thrown if UERANSIM is run inside a container without stdin and tty

### ISSUE THREAD

**Issue by herlesupreeth** [aligungr/UERANSIM#183]
```
Creating ueransim ... done
Attaching to ueransim
ueransim  | WARNING: All global logs are written to: logs/global.log
ueransim  | WARNING: All logs of UEs and gNBs are written to their own log files: logs/*
ueransim  | WARNING: All load testing logs are written to: logs/loadtest.log
ueransim  | INFO: Selected profile: "open5gs"
ueransim  | [2020-11-15 16:24:45.384] [SUCCESS] [PROCEDURE_RESULT] [gnb-1] NGSetup procedure is successful
ueransim  | -----------------------------------------------------------------------------
ueransim  | List of possible tests:
ueransim  | 1) initial-registration
ueransim  | 2) periodic-registration
ueransim  | 3) de-registration
ueransim  | 4) pdu-session-establishment
ueransim  | Selection: 
ueransim  | Exception in thread "main" java.util.NoSuchElementException: No line found
ueransim  | 	at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
ueransim  | 	at tr.havelsan.ueransim.app.app.entry.MainApp.main(MainApp.java:37)

```

Above is the log i get when running inside the container, please let me know if you need further information

**Comment by aligungr** [comment]
@herlesupreeth 
Thanks for the pull request. I am merging it to master.

Also for your information, we are working on a web interface in order to use UERANSIM without a terminal access. (Currently there is no way to use it without a terminal)

**Comment by herlesupreeth** [comment]
I managed to get it running docker-compose as follows:

Have the following in docker-compose file

```
stdin_open: true
tty: true
```

and run the

docker-compose -f <docker-compose-file> up -d && docker attach <container-name-to-attach-to>

Really, awesome SW to test 5G Core. Thanks a lot
