### ISSUE TITLE
no constructor found for given parameter names for type UeConfig

### ISSUE THREAD

**Issue by lukedevon** [aligungr/UERANSIM#187]
Hi, 

I have installed and configured the UERANSIM in the same Linux box where the open5gs have installed. I didn't have any problem with the installation. But when I am executing the $sudo sh run.sh, I got the following message;

[2020-11-18 15:53:25.758] [INFO] [CONNECTION] [gnb-1] SCTP connection established
Exception in thread "main" tr.havelsan.ueransim.mts.MtsException: no constructor found for given parameter names for type UeConfig

and I don't get the "List of possible tests" menu. 

May I know what could be wrong that I have made? 
------------------------------------------------------
Complete message:
============
INFO: Selected profile: "open5gs"
[2020-11-18 15:53:25.579] [INFO] [CONNECTION] [air] TUN Bridge has been started.
[2020-11-18 15:53:25.735] [INFO] [CONNECTION] [gnb-1] Trying to establish SCTP connection... (127.0.0.5:38412)
[2020-11-18 15:53:25.758] [INFO] [CONNECTION] [gnb-1] SCTP connection established
Exception in thread "main" tr.havelsan.ueransim.mts.MtsException: no constructor found for given parameter names for type UeConfig
        at tr.havelsan.ueransim.mts.MtsConstruct.construct(MtsConstruct.java:99)
        at tr.havelsan.ueransim.mts.MtsConstruct.construct(MtsConstruct.java:163)
        at tr.havelsan.ueransim.app.app.AppConfig.createUeConfig(AppConfig.java:41)
        at tr.havelsan.ueransim.app.app.UeRanSim.initialize(UeRanSim.java:69)
        at tr.havelsan.ueransim.app.app.UeRanSim.<init>(UeRanSim.java:53)
        at tr.havelsan.ueransim.app.app.AppBuilder.build(AppBuilder.java:75)
        at tr.havelsan.ueransim.app.app.entry.MainApp.main(MainApp.java:20)
[2020-11-18 15:53:26.863] [SUCCESS] [PROCEDURE_RESULT] [gnb-1] NGSetup procedure is successful

Thanks
Luke.

**Comment by aligungr** [comment]
Hi Luke

Please make sure that `ue.yaml` file does not contain invalid parameters. You can look at the reference config file [here](https://github.com/aligungr/UERANSIM/blob/master/config/open5gs/ue.yaml).

If that does not solve the problem, you can post the `ue.yaml` file here.

**Comment by lukedevon** [comment]
Hi aligungr, 

You are right. I have made a mistake when updating parameters. Mange to fix it by going through the sample config file that you have provided. All good now. 

Thanks
Luke
