### ISSUE TITLE
free5gc-stage3.0.4 create UE fail

### ISSUE THREAD

**Issue by j13tw** [aligungr/UERANSIM#235]
Hi, I am testing the free5gc stage 3.0.4 in kubernetes cluster environment
all free5gc vNFs are containerlize build from "free5gmano" provided yaml file and image
wait for all vNFs are ```Running``` status in my cluster, 
then after use free5gc provided webUI create subscriber and change ```opc -> op```
and use  the ```config/free5gc/ue.yaml``` subscriber default information
after all free5gc setup in my cluster
I build the UERANSIM project with Container Image and run it in my cluster
use ```./nr-agent``` running free5gc profile  in daemon
I run the command follow the wiki to send the ```gnb-create -> ue-create``` with ```./nr-cli```
and when send command ```ue-create```
It tell me some issue
```
root@ueramsim-deployment-5d495cf4dc-lmdbk:/UERANSIM# ./nr-cli ue-create
UE created: imsi-208930000000003.

2021-01-25 04:16:58.800 [INFO] [STATE] [ue-208930000000003] UE switches to state: MM_DEREGISTERED/MM_DEREGISTERED__PLMN_SEARCH
2021-01-25 04:16:59.002 [INFO] [CONN] [ue-208930000000003] UE connected to gNB.
2021-01-25 04:16:59.003 [INFO] [STATE] [ue-208930000000003] UE switches to state: MM_DEREGISTERED/MM_DEREGISTERED__NORMAL_SERVICE
2021-01-25 04:16:59.103 [INFO] [STATE] [ue-208930000000003] UE switches to state: MM_REGISTERED_INITIATED/MM_REGISTERED_INITIATED__NA
Exception in thread "Thread-22" tr.havelsan.ueransim.utils.exceptions.ReservedOrInvalidValueException: invalid or reserved value found for <EExtendedProtocolDiscriminator> with value <0>
	at tr.havelsan.ueransim.nas.core.ProtocolEnum.fromValueGeneric(ProtocolEnum.java:53)
	at tr.havelsan.ueransim.nas.impl.enums.EExtendedProtocolDiscriminator.fromValue(EExtendedProtocolDiscriminator.java:24)
	at tr.havelsan.ueransim.nas.NasDecoder.nasPdu(NasDecoder.java:48)
	at tr.havelsan.ueransim.nas.NasDecoder.nasPdu(NasDecoder.java:31)
	at tr.havelsan.ueransim.nas.NasDecoder.nasPdu(NasDecoder.java:42)
	at tr.havelsan.ueransim.app.ue.nas.sec.NasSecurity.decryptNasMessage(NasSecurity.java:44)
	at tr.havelsan.ueransim.app.ue.nas.NasTransport.receiveNas(NasTransport.java:43)
	at tr.havelsan.ueransim.app.ue.nas.NasTask.receiveDownlinkNas(NasTask.java:73)
	at tr.havelsan.ueransim.app.ue.nas.NasTask.main(NasTask.java:59)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

for this problem, 
I give my UERANSIM log file, 
maybe you can help me fix or check some value in UERANSIM to send to free5gc vNFs
or tell me which free5gc version are UERANSIM Supported.
thx!

[gnb-1.log ](https://github.com/aligungr/UERANSIM/files/5864246/gnb-1.log)
[ue-208930000000003.log ](https://github.com/aligungr/UERANSIM/files/5864245/ue-208930000000003.log)
[amf.log](https://github.com/aligungr/UERANSIM/files/5864247/amf.log)

**Comment by aligungr** [comment]
Hi @j13tw It may be related to https://github.com/free5gc/free5gc/issues/104.

Please send a pcap file to analyze the problem.

**Comment by j13tw** [comment]
Hello @aligungr, 
I try to build the nighty build free5gc stage3.0.4 version
and also reply the same of error as I post it.
I think the error maybe is the free5gc vNFs error,
and here is my setup vNFs config in free5gmano ( [link-of-config](https://github.com/free5gmano/free5gmano/blob/master/deploy/free5gc-stage-3.0.4/k8s-cni/00-free5gc-configmap.yaml))
and I fix the amfcfg ```ngapIp``` same of the pod IP, 
and smfcfg ```node_id```same of the UPF pod IP
[ueransim-pcap.txt](https://github.com/aligungr/UERANSIM/files/5866080/ueransim-pcap.txt)
here, I will give you my testing ueransim command pod's pcap, 
and the all free5gc vNFs IP follow the figure,
have any pcap of fre5gc vNFs you need to analyze it, please tell me!
Tks!

<img width="1440" alt="截圖 2021-01-25 下午6 51 16" src="https://user-images.githubusercontent.com/27864573/105697852-0ae11180-5f40-11eb-855b-9049b994159a.png">

**Comment by j13tw** [comment]
Hello @aligungr,
I rebuild the v3.0.2 UERANSIM project
and I check the free5gc amf config for my free5gc-configmap
the UERANSIM is work well for me, thanks!

**Comment by aligungr** [comment]
Hi @j13tw, That's nice, glad to hear that.
