### ISSUE TITLE
java -jar ueransim-1.0.8.jar running error

### ISSUE THREAD

**Issue by Iverson-Zheng** [aligungr/UERANSIM#85]
Hello everyone, I have updated the code to the latest type  but I met the problem when running this simulartor. The error information is shown below.
```
Exception in thread "main" tr.havelsan.ueransim.mts.MtsException: file not found: config/root.yaml
	at tr.havelsan.ueransim.mts.MtsInitializer.lambda$initMts$0(MtsInitializer.java:82)
	at tr.havelsan.ueransim.mts.MtsDecoder.decode(MtsDecoder.java:47)
	at tr.havelsan.ueransim.AppConfig.initialize(AppConfig.java:55)
	at tr.havelsan.ueransim.Program.main(Program.java:52)
```
If you met this error before or have some suggetions, Please tell me .
Thank you bery much

**Comment by Iverson-Zheng** [comment]
In fact, the root.yaml existed under the directory config

**Comment by aligungr** [comment]
@Iverson-Zheng Just use `./build.sh` to build the app, and use `./run.sh` to run the app. In this way it should work.

**Comment by Iverson-Zheng** [comment]
> @Iverson-Zheng Just use `./build.sh` to build the app, and use `./run.sh` to run the app. In this way it should work.
> 
> No need to execute `java -jar` manually.

OK, Thank you. I will have a try.

**Comment by mimo123-code** [comment]
/.build.sh is not working even after setting the path
